Quality Gate Added

diff --git a/.cloudbees/workflows/main-workflow.yaml b/.cloudbees/workflows/main-workflow.yaml
--- a/.cloudbees/workflows/main-workflow.yaml
+++ b/.cloudbees/workflows/main-workflow.yaml
@@ -5,6 +5,8 @@ on:
   push:
     branches:
       - "**"
+  workflow_dispatch:
+    
 permissions:
   scm-token-own: read
   scm-token-org: read
@@ -159,15 +161,14 @@ jobs:
             | MINOR_COUNT          | ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }} |
           format: MARKDOWN
 
-      # - name: Quality gate
-      #   if: ${{ fromJSON(steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT) > 3 }} 
-      #   uses: docker://alpine:3.18
-      #   run: |
-      #     echo "Scan gate failed: Unacceptable quality threshold"
-      #     exit 1
+      - name: Quality gate
+        if: ${{ fromJSON(steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT) > 0 }} 
+        uses: docker://alpine:3.18
+        run: |
+          echo "Scan gate failed: Unacceptable quality threshold"
+          exit 1
 
   deploy:
-## SPIKE-BUSTER to enter a CBC interogtation step here. 
     environment: DOW Production
     steps:
       - name: Checkout
